[package]
name = "portal-os"
version = "0.1.0-alpha.2"
edition = "2024"
authors = ["Wenju Guo"]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
chrono = { version = "0.4", features = ["serde"] }
axum = { version = "0.8.7", features = ["multipart", "json", "tracing", "ws"] }
tower-http = { version = "0.6.6", features = ["trace", "cors", "limit", "timeout"] }
tokio = { version = "1", features = ["full"] }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt", "chrono"] }
anyhow = { version = "1.0.100" }
rust-embed = { version = "8.4.0" }
mime_guess = { version = "2.0.4" }
clap = { version = "4", features = ["derive"] }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
argon2 = { version = "0.5" }
rand = { version = "0.9" }
sha2 = { version = "0.10" }
hex = { version = "0.4" }
dotenvy = { version = "0.15" }
pulldown-cmark = { version = "0.13" }
ammonia = { version = "4" }
shadow-rs = { version = "1.4.0", features = ["metadata"] }
sqlx = { version = "0.9.0", default-features = false, features = ["runtime-tokio", "sqlite", "macros", "migrate"] }

[build-dependencies]
anyhow = "1"                                   
shadow-rs = "1"     

[profile.release]
strip = true
lto = "fat"

[profile.dev]
incremental = true
