[package]
name = "portal-os"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
axum = { workspace = true, features = ["multipart", "json", "tracing", "ws"] }
tower-http = { workspace = true, features = ["trace", "cors", "limit", "timeout"] }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt", "chrono"] }
shadow-rs = { workspace = true, features = ["metadata"] }
anyhow = { workspace = true }
rust-embed = { workspace = true }
mime_guess = { workspace = true }
clap = { workspace = true, features = ["derive"] }
reqwest = { workspace = true, features = ["json", "rustls-tls"] }
toasty = { workspace = true, features = ["sqlite"] }
toasty-driver-sqlite = { workspace = true }
argon2 = { workspace = true }
rand = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
dotenvy = { workspace = true }


[build-dependencies]
anyhow = { workspace = true }                                   
shadow-rs = { workspace = true }                           
